### ISSUE TITLE
Lots of credit to go around

### ISSUE THREAD

**Issue by lemire** [eddelbuettel/rcppsimdjson#2]
It is not quite fair to attribute simdjson to Geoff and myself.

**Comment by eddelbuettel** [comment]
Excellent point -- and please feel free to PR away as you see fit -- it is this type of correction I was thinking / hoping you could make.  

And/or point me to another document or paragraph in the simdjson repo I could borrow from.

**Comment by eddelbuettel** [comment]
I had a stab at it, which hopefully improves it a little.  Thanks for pointing it out.
