### ISSUE TITLE
utils::download.file()

### ISSUE THREAD

**Issue by knapply** [eddelbuettel/rcppsimdjson#29]
@eddelbuettel  There are packages on CRAN with an identical `NOTE`. Do you have a policy/preference here?

[Travis Log](https://travis-ci.org/github/eddelbuettel/rcppsimdjson/jobs/703737053#L286-L291)
```
* checking R code for possible problems ... NOTE
fload: no visible global function definition for ‘download.file’
Undefined global functions or variables:
  download.file
Consider adding
  importFrom("utils", "download.file")
to your NAMESPACE file.
```

Code affected:
https://github.com/eddelbuettel/rcppsimdjson/blob/60e3d3f0d231ed3c793220715e9f42f1237d7472/R/fload.R#L182-L183

**Comment by eddelbuettel** [comment]
As we use it, and `R CMD check` even suggests it we should _of course_ add `importFrom("utils", "download.file")` to `NAMESPACE`.  Or am I missing some meta conversation here?   Also, why would we care what errors other packages make? ;-)

**Comment by eddelbuettel** [comment]
I appreciate you asked.  But on the margin. that is the type of one-line change you could just have committed.  Or, better still, in a joint repo, put the one line change in PR, I look and nod and you merge and move on.

Some things really _are_ that simple :)
