### ISSUE TITLE
unlink woes

### ISSUE THREAD

**Issue by knapply** [eddelbuettel/rcppsimdjson#33]
https://twitter.com/michael_chirico/status/1280675491448410113

"just poking around so I may be wrong, but it looks like that unlink should be diagnosis$input[[i]]?"

![image](https://user-images.githubusercontent.com/26281249/86864650-691cd480-c082-11ea-89f5-d50bac4132ed.png)

Once upon a time it was only URLs or only files. and `unlink()` would only affect downloaded files. That's no longer the case.

**Comment by eddelbuettel** [comment]
That was too short-hand for me.  Maybe copy the tweet text time.

Bugs happen. I created millions in my day.  Life goes on.  Reasons for 0.1.1 :)

**Comment by eddelbuettel** [comment]
Thanks for the edit. I got there eventually. (It doesn't help that Chrome+Twitter, the combo of adblockers I have, don't directly send me to the tweet (high _wtf_ factor here) so I always have to go a send time in incognito mode.  Ahh the 1st world problems we have.  Now you have know why I whine about directly quoting ;-)

BTW looks like you pushed on "empty" ie "unchanged" branch in issue/33.  On purpose?

**Comment by knapply** [comment]
Yes, it was intentional.

**Comment by eddelbuettel** [comment]
Gotta love a good baseline to compare to :)

**Comment by eddelbuettel** [comment]
Done in #34
