### ISSUE TITLE
CRAN Mac fails where clang and gcc are fine

### ISSUE THREAD

**Issue by knapply** [eddelbuettel/rcppsimdjson#48]
https://www.r-project.org/nosvn/R.check/r-release-macos-x86_64/RcppSimdJson-00check.html

Adding `#include <optional>` to inst/include/RcppSimdJson/utils.hpp should do be all that's needed.

**Comment by eddelbuettel** [comment]
Confirmed, belatedly, at RHub.

**Comment by eddelbuettel** [comment]
That was spot-on and took care of business.
