### ISSUE TITLE
WISH: Add URL and BugReports

### ISSUE THREAD

**Issue by HenrikBengtsson** [eddelbuettel/rcppsimdjson#50]
Just dropping by to ask for a URL and BugReports in DESCRIPTION to make it easier to find this repos from CRAN.

**Comment by eddelbuettel** [comment]
Sure.  But please explain to me how having a static URL link to GH helps with CRAN discoverability.

**Comment by HenrikBengtsson** [comment]
> ... to find this [GitHub] repos from CRAN.
