### ISSUE TITLE
simdjson 0.9.0

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/rcppsimdjson#69]
This seems related to #53 in that the on-demand API is now put to the fore (per the tweet announcement by @lemire).

Sadly, just copying the two `singleheader/` files in as I attempted in a branch breaks our compilation in lots of places :cry:

**Comment by lemire** [comment]
@eddelbuettel We fully support the DOM API. I am sure it is only small stuff that fails.

**Comment by lemire** [comment]
Oh. I see. I will prepare a pull request.

**Comment by lemire** [comment]
I am working on a pull request. We effectively blocked what you are doing which is bypassing entirely the error handling. The way you did it is fine, I am sure, but people would bypassing checking the error and they complaining that they were getting garbage... so we are now forcing people to handle errors or to have exceptions.

People doing no error checking at all is a nightmare for us.

**Comment by eddelbuettel** [comment]
Thank you so much.  @knapply is currently in transit but hopes to get a chance to look at it later today.  There is not need to rush, I guess, as there are really two possible approaches
- renable DOM we used / are using
- change our code to on-demand (which we already planned by didn't get to yet), see #53

And latter one is, I guess, preferred by all but a little more work.

**Comment by lemire** [comment]
@eddelbuettel There is no need to reenable anything. You will see.

**Comment by lemire** [comment]
On Demand (https://github.com/eddelbuettel/rcppsimdjson/issues/53) would definitively be the way forward. It would enable really cool things and improve performance.

**Comment by eddelbuettel** [comment]
We have 1.0.0; the on-demand feature is still WIP and harder given R's memory interface...
