### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by kforner** [eddelbuettel/rcppsimdjson#84]
Just wanted to say thank you for that incredibly useful software.

**Comment by eddelbuettel** [comment]
You are more than welcome Karl -- the real credit goes to @lemire and co-authors for another rocking library (among many others) and to @knapply for driving the package much further right after I started it.

**Comment by kforner** [comment]
Yes of course I also thank them very much!
 I watched LeMire's video on simdjson at QCON and it was enlightening and funny. And I love his English, very French-friendly.
