### ISSUE TITLE
Bug in validate benchmark?

### ISSUE THREAD

**Issue by anthonynorth** [eddelbuettel/rcppsimdjson#89]
There looks to be a bug in the validate json benchmark. {yyjsonr} is reading a file into memory instead of validating it.

https://github.com/eddelbuettel/rcppsimdjson/blob/7100cac4172e904171e8874563d21cbcd13938df/demo/simpleBenchmark.R#L19

I think this should be:
```R
yyjsonr = yyjsonr::validate_json_file(file),
```

**Comment by eddelbuettel** [comment]
My bad, I will fix that.

**Comment by eddelbuettel** [comment]
Now done, thanks for catching that.
