### ISSUE TITLE
CRAN warnings with g++-14

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/rcppsimdjson#91]
Via email from CRAN:

<blockquote>

Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_RcppSimdJson.html>.

Please correct before 2024-08-03 to safely retain your package on CRAN.

This is primarily about the compiler C++ warnings
shown in the fedora-gcc results.  These are from g++ 14.x
which was released a couple of months ago.

The CRAN Team

</blockquote>

which shows both via https://cran.r-project.org/web/checks/check_results_RcppSimdJson.html directly and the 'gcc12' link

<blockquote>

* checking whether package ‘RcppSimdJson’ can be installed ... [241s/251s] WARNING
Found the following significant warnings:
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:14229:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:14230:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:14232:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:16393:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:16394:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:16396:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:20872:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/../../simdjson.h:20873:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/Rc
ppSimdJson/deserialize/../../simdjson.h:20875:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/RcppSimdJson/deserialize/Type_Doctor.hpp:43:65: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:14229:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:14230:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:14232:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:16393:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:16394:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:16396:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:20872:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:20873:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  ../inst/include/simdjson.h:20875:32: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
See ‘/data/gannet/ripley/R/packages/tests-devel/RcppSimdJson.Rcheck/00install.out’ for details.
* used C++ compiler: ‘g++-14 (GCC) 14.1.0’

</blockquote>

Any sage advice here @lemire ?  I guess I could hardwire C++17 as a standard in the short-term but I presume 'eventually' we need to make a change.

Now, it could well be that the change is already made upstream -- I have not sync'ed in a while.  If so just let me know....

Dirk (in Europe for a few more days)

**Comment by lemire** [comment]
See https://github.com/eddelbuettel/rcppsimdjson/pull/92 where I propose a version bump.

The simdjson library is kept up-to-date and tested with all major compilers with almost all possible flags, including C++20.

**Comment by eddelbuettel** [comment]
You rock, and thank you from Athens airport.
